# Generated by Django 4.0.5 on 2022-06-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_book_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
    ]
