# Generated by Django 4.0.5 on 2022-06-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_book_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.CharField(max_length=5, verbose_name='number'),
        ),
    ]
